name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    env:
      SKIP: terraform-docs-system
      TF_IN_AUTOMATION: "true"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"
          terraform_wrapper: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Set up TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check README docs
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          working-dir: .
          config-file: .terraform-docs.yml
          fail-on-diff: "true"
          git-push: "false"

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"
          terraform_wrapper: false

      - name: Initialize Terraform
        run: terraform init -backend=false -no-color

      - name: Run terraform tests
        run: terraform test -no-color
